In [8]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print(torch.__version__)

2.5.1+cu121


PyTorch tensors are created using torch.tensor() - https://pytorch.org/docs/stable/tensors.html

In [9]:
#scalar
scalar = torch.tensor(7)
scalar
#vector
vector = torch.tensor([7,7])
vector.ndim
#tensor
TENSOR = torch.tensor([[[1,3],[2,3],[3,4]],
                       [[1,2],[2,3],[3,4]]])
TENSOR.shape

torch.Size([2, 3, 2])

In [10]:
rand_tensor = torch.rand(4,3)
rand_tensor.shape, rand_tensor.ndim

(torch.Size([4, 3]), 2)

In [11]:
zeros = torch.zeros(size = (4,1))
zeros*rand_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

`torch.arange(start= , end = , step =)`

`torch_like(input = )`



dtype = torch.float16 blah blah....


In [12]:
f32_tensor = torch.tensor([3.0,2.0], dtype = None,#what datatype
                                      device = None,
                                  requires_grad = False)
f32_tensor.dtype

#to convert

f16_tensor = f32_tensor.type(torch.float16)
f16_tensor*f32_tensor


tensor([9., 4.])

###Info handling

to get tensor datatype - tensor.dtype

to get ttensor shape - tensor.shape

to get tensor device - tensor.device

tensor.matmul
tensor.T for transposing

In [13]:
riga = torch.rand(3,2) @ torch.rand(2,3)
torch.min(riga), torch.max(riga), riga.min(), riga.max()
riga.mean(), riga.sum()


(tensor(0.4185), tensor(3.7663))

In [14]:
# use to get index of max and min
riga.argmin(), riga.argmax()


(tensor(8), tensor(4))

In [15]:
riga = riga.reshape(1,3,3)
torch.vstack([riga,riga]).shape, torch.stack([riga,riga], dim =0).shape,riga.squeeze().unsqueeze(dim=0).shape

#for unsqueeze, a dimension can be added at any index depending on dim = '', can also use negative indexing

(torch.Size([2, 3, 3]), torch.Size([2, 1, 3, 3]), torch.Size([1, 3, 3]))

In [16]:
riga.permute(1,2,0)
rigved=riga.view(3,3) #view basically shares the same memory as the original tensor, any changes to the view results in changes to the og tensor
rigved[0,0]=0
riga


tensor([[[0.0000, 0.7669, 0.4933],
         [0.3053, 0.7737, 0.5073],
         [0.1875, 0.2625, 0.1414]]])

In [17]:
import torch

tensor = torch.arange(1,10.1,)
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [18]:


import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.7958, 0.0308, 0.7985, 0.3237],
        [0.4879, 0.4810, 0.0840, 0.3417],
        [0.5418, 0.4885, 0.4143, 0.6817]])

Tensor B:
tensor([[0.3133, 0.2154, 0.7209, 0.7025],
        [0.1347, 0.2735, 0.7633, 0.8289],
        [0.7668, 0.5222, 0.7953, 0.7734]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens# just use torch.manual_seed no need to use torch.random.manual_seed()
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [20]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')



Instead, to get a tensor back to CPU and usable with NumPy we can use Tensor.cpu().

This copies the tensor to CPU memory so it's usable with CPUs.


In [21]:

# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

###Practice

In [22]:
import torch

seed = 0
torch.cuda.manual_seed(seed)
torch.manual_seed(1234)
a= torch.rand(7,7,device= "cuda")
torch.manual_seed(1234)
b= torch.rand(1,7,device= "cuda")
torch.manual_seed(7)
c=torch.rand(1,1,1,10)
c, c.squeeze()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))